AUDIENCE="api.example.com" \
EXPIRATION=60 \
HOST="0.0.0.0" \
ISSUER="https://login.helloprima.com" \
PORT=4000 \
RNG_SEED=0 \
SECRET="c2VjcmV0" \
USER__ADDRESS__COUNTRY="US" \
USER__ADDRESS__LOCALITY="Los Angeles" \
USER__ADDRESS__POSTAL_CODE="90210" \
USER__ADDRESS__REGION="CA" \
USER__ADDRESS__STREET_ADDRESS="123 Hollywood Blvd." \
USER__EMAIL_VERIFIED="true" \
USER__EMAIL="john.doe@example.com" \
USER__FAMILY_NAME="Doe" \
USER__GIVEN_NAME="John" \
USER__LOCALE="en-US" \
USER__MIDDLE_NAME="James" \
USER__NAME="John Doe" \
USER__NICKNAME="Jimmy" \
USER__PHONE_NUMBER="+1 (425) 555-1212" \
USER__PROFILE="https://example.com/john.doe" \
USER__UPDATED_AT=1311280970 \
USER__ZONEINFO="America/Los_Angeles" \
cargo run
